from typing import List, Dict

SKILL_LEXICON: Dict[str, List[str]] = {
    "Python": ["python", "питон"],
    "FastAPI": ["fastapi"],
    "Django": ["django"],
    "Flask": ["flask"],
    "SQL": ["sql", "postgres", "postgresql", "mysql", "oracle sql", "sql server"],
    "Airflow": ["airflow", "apache airflow"],
    "Kafka": ["kafka", "apache kafka"],
    "Spark": ["spark", "pyspark", "apache spark"],
    "Docker": ["docker", "докер"],
    "Kubernetes": ["kubernetes", "k8s", "кубернетес", "кубер"],
    "Git": ["git", "гит"],
    "Linux": ["linux", "линукс", "unix"],
    "ETL": ["etl", "elt", "data pipeline", "интеграция данных"],
    "Power BI": ["powerbi", "power bi"],
    "Pandas": ["pandas"],
    "NumPy": ["numpy"],
    "REST": ["rest", "rest api", "api", "http api"],
    "GraphQL": ["graphql"],
    "CI/CD": ["ci/cd", "ci cd", "конвейеры", "pipelines", "continuous integration", "continuous delivery", "continuous deployment"],
    "English B1+": ["английский b1", "английский b2", "english b1", "english b2", "intermediate english"],

    "JavaScript": ["javascript", "js", "ecmascript"],
    "TypeScript": ["typescript", "ts"],
    "Node.js": ["node.js", "nodejs", "node"],
    "Express": ["express", "express.js"],
    "NestJS": ["nestjs", "nest.js", "nest"],
    "React": ["react", "reactjs", "react.js"],
    "Redux Toolkit": ["redux toolkit", "rtk", "redux-toolkit", "redux"],
    "Next.js": ["next", "nextjs", "next.js"],
    "Vue.js": ["vue", "vuejs", "vue.js"],
    "Nuxt.js": ["nuxt", "nuxtjs", "nuxt.js"],
    "Angular": ["angular", "angularjs", "ng"],
    "Svelte": ["svelte"],
    "SvelteKit": ["sveltekit"],
    "SolidJS": ["solid", "solidjs"],
    "Vite": ["vite"],
    "Webpack": ["webpack"],
    "Rollup": ["rollup"],
    "Parcel": ["parcel"],
    "Babel": ["babel"],
    "ESLint": ["eslint"],
    "Prettier": ["prettier"],
    "Jest": ["jest"],
    "Mocha": ["mocha"],
    "Chai": ["chai"],
    "Cypress": ["cypress"],
    "Playwright": ["playwright"],
    "Selenium": ["selenium", "selenium webdriver", "webdriver"],
    "Storybook": ["storybook"],
    "Tailwind CSS": ["tailwind", "tailwindcss", "tailwind css"],
    "Bootstrap": ["bootstrap", "bs"],
    "Material UI": ["mui", "material ui", "material-ui"],
    "Ant Design": ["ant design", "antd"],
    "tRPC": ["trpc"],
    "gRPC": ["grpc", "g rpc"],
    "WebSocket": ["websocket", "ws", "web sockets"],
    "SOAP": ["soap"],
    "OpenAPI/Swagger": ["openapi", "swagger", "swagger ui", "swaggerhub"],
    "Postman": ["postman"],
    "Insomnia": ["insomnia"],

    "Java": ["java"],
    "Spring Boot": ["spring boot", "spring-boot", "spring"],
    "Hibernate": ["hibernate", "jpa"],
    "Maven": ["maven"],
    "Gradle": ["gradle"],
    "Scala": ["scala"],
    "SBT": ["sbt"],
    "Kotlin": ["kotlin", "kt"],
    "Go": ["go", "golang"],
    "Gin": ["gin", "gin-gonic"],
    "Fiber": ["fiber", "gofiber"],
    "Java EE": ["java ee", "jakarta ee", "jakarta"],
    ".NET": [".net", "dotnet", ".net core", "asp.net", "asp.net core"],
    "C#": ["c#", "c sharp", "c-sharp"],
    "C++": ["c++", "cpp"],
    "C": ["c"],
    "Rust": ["rust"],
    "PHP": ["php"],
    "Laravel": ["laravel"],
    "Symfony": ["symfony"],
    "Ruby": ["ruby"],
    "Rails": ["rails", "ruby on rails", "ror"],
    "Elixir": ["elixir"],
    "Phoenix": ["phoenix"],
    "R": ["r"],
    "Julia": ["julia"],
    "MATLAB": ["matlab"],
    "Bash": ["bash", "shell", "sh"],
    "PowerShell": ["powershell", "ps", "ps1"],

    "Ansible": ["ansible"],
    "Terraform": ["terraform", "tf"],
    "Pulumi": ["pulumi"],
    "CloudFormation": ["cloudformation", "cfn"],
    "Packer": ["packer", "hashicorp packer"],
    "Helm": ["helm", "helm charts"],
    "Argo CD": ["argo cd", "argocd"],
    "Flux": ["flux", "fluxcd"],
    "Argo Workflows": ["argo workflows", "argo"],
    "Nomad": ["nomad", "hashicorp nomad"],
    "Consul": ["consul", "hashicorp consul"],
    "Vault": ["vault", "hashicorp vault"],
    "OpenShift": ["openshift", "red hat openshift", "ocp"],
    "Docker Compose": ["docker compose", "docker-compose", "compose"],
    "Podman": ["podman"],
    "Istio": ["istio"],
    "Linkerd": ["linkerd"],
    "Envoy": ["envoy", "envoy proxy"],
    "Nginx": ["nginx", "engine x"],
    "Traefik": ["traefik"],
    "HAProxy": ["haproxy", "ha proxy"],
    "Apache HTTPD": ["apache", "httpd", "apache httpd"],

    "PostgreSQL": ["postgresql", "postgres", "постгрес"],
    "MySQL": ["mysql"],
    "MariaDB": ["mariadb", "maria db"],
    "SQLite": ["sqlite", "sqlite3"],
    "Microsoft SQL Server": ["sql server", "mssql", "ms sql"],
    "Oracle Database": ["oracle", "oracle db", "oracle database"],
    "MongoDB": ["mongodb", "mongo", "монгодб"],
    "Redis": ["redis", "редис"],
    "Memcached": ["memcached"],
    "Elasticsearch": ["elasticsearch", "es"],
    "OpenSearch": ["opensearch"],
    "Solr": ["solr", "apache solr"],
    "ClickHouse": ["clickhouse"],
    "Cassandra": ["cassandra", "apache cassandra"],
    "Neo4j": ["neo4j", "graph db", "graph database"],
    "InfluxDB": ["influxdb"],
    "TimescaleDB": ["timescaledb", "timescale"],
    "Snowflake": ["snowflake"],
    "Amazon Redshift": ["redshift", "aws redshift"],
    "Google BigQuery": ["bigquery", "gcp bigquery"],
    "Vertica": ["vertica"],
    "Teradata": ["teradata"],
    "Apache Druid": ["druid", "apache druid"],
    "Hive": ["hive", "apache hive"],
    "HBase": ["hbase", "apache hbase"],
    "Presto": ["presto", "prestodb"],
    "Trino": ["trino", "presto sql"],
    "Impala": ["impala", "apache impala"],

    "Hadoop": ["hadoop", "apache hadoop", "hdfs"],
    "HDFS": ["hdfs"],
    "YARN": ["yarn", "hadoop yarn"],
    "Flink": ["flink", "apache flink"],
    "NiFi": ["nifi", "apache nifi"],
    "Debezium": ["debezium"],
    "Kafka Connect": ["kafka connect", "connect"],
    "Kafka Streams": ["kafka streams"],
    "Spark Streaming": ["spark streaming", "structured streaming"],

    "Parquet": ["parquet", "apache parquet"],
    "Avro": ["avro", "apache avro"],
    "ORC": ["orc", "apache orc"],
    "JSON": ["json"],
    "YAML": ["yaml", "yml"],
    "XML": ["xml"],
    "Protocol Buffers": ["protobuf", "protocol buffers", "proto"],

    "Delta Lake": ["delta lake", "delta"],
    "Apache Iceberg": ["iceberg", "apache iceberg"],
    "Apache Hudi": ["hudi", "apache hudi"],

    "Luigi": ["luigi"],
    "Prefect": ["prefect"],
    "Dagster": ["dagster"],

    "dbt": ["dbt", "data build tool"],
    "Airbyte": ["airbyte"],
    "Fivetran": ["fivetran"],
    "Talend": ["talend"],
    "Informatica": ["informatica"],
    "Pentaho": ["pentaho", "kettle", "pentaho kettle"],

    "RabbitMQ": ["rabbitmq", "rabbit"],
    "ActiveMQ": ["activemq", "apache activemq"],
    "NATS": ["nats"],
    "MQTT": ["mqtt"],
    "Amazon SQS": ["sqs", "aws sqs"],
    "Amazon SNS": ["sns", "aws sns"],
    "Google Pub/Sub": ["pubsub", "google pubsub", "gcp pub/sub"],
    "NSQ": ["nsq"],
    "ZeroMQ": ["zeromq", "0mq", "zmq"],

    "Celery": ["celery"],
    "RQ": ["rq", "redis queue"],

    "Prometheus": ["prometheus"],
    "Grafana": ["grafana"],
    "Loki": ["loki", "grafana loki"],
    "Jaeger": ["jaeger"],
    "OpenTelemetry": ["opentelemetry", "otel"],
    "ELK Stack": ["elk", "elastic stack", "elasticsearch logstash kibana"],
    "EFK Stack": ["efk", "elasticsearch fluentd kibana"],
    "Logstash": ["logstash"],
    "Kibana": ["kibana"],
    "Fluentd": ["fluentd"],
    "Fluent Bit": ["fluent bit", "fluent-bit"],
    "Graylog": ["graylog"],

    "OAuth 2.0": ["oauth2", "oauth 2", "oauth 2.0"],
    "OpenID Connect": ["openid connect", "oidc"],
    "JWT": ["jwt", "json web token"],
    "Keycloak": ["keycloak"],
    "Okta": ["okta"],
    "Auth0": ["auth0"],

    "Kong": ["kong"],
    "Tyk": ["tyk"],
    "KrakenD": ["krakend"],
    "Apigee": ["apigee"],

    "AWS": ["aws", "amazon web services"],
    "GCP": ["gcp", "google cloud", "google cloud platform"],
    "Azure": ["azure", "microsoft azure"],
    "Yandex Cloud": ["yandex cloud", "yc", "яндекс облако"],
    "DigitalOcean": ["digitalocean", "do"],
    "Heroku": ["heroku"],

    "AWS Lambda": ["lambda", "aws lambda"],
    "Amazon S3": ["s3", "aws s3"],
    "Amazon EC2": ["ec2", "aws ec2"],
    "AWS IAM": ["iam", "aws iam"],
    "GCP Cloud Functions": ["cloud functions", "gcp cloud functions"],
    "Azure Functions": ["azure functions"],
    "Azure DevOps": ["azure devops"],

    "scikit-learn": ["scikit-learn", "sklearn"],
    "TensorFlow": ["tensorflow", "tf"],
    "Keras": ["keras"],
    "PyTorch": ["pytorch", "torch"],
    "XGBoost": ["xgboost"],
    "LightGBM": ["lightgbm", "lgbm"],
    "CatBoost": ["catboost"],
    "MLflow": ["mlflow"],
    "DVC": ["dvc", "data version control"],
    "Kubeflow": ["kubeflow"],
    "Metaflow": ["metaflow"],
    "TFX": ["tfx", "tensorflow extended"],
    "ONNX": ["onnx"],
    "Hugging Face": ["hugging face", "transformers", "hf transformers"],
    "spaCy": ["spacy"],
    "NLTK": ["nltk"],
    "Optuna": ["optuna"],
    "Ray": ["ray", "ray tune", "ray serve"],
    "Weights & Biases": ["wandb", "weights and biases"],

    "Matplotlib": ["matplotlib", "mpl"],
    "Seaborn": ["seaborn", "sns"],
    "Plotly": ["plotly"],
    "Bokeh": ["bokeh"],
    "Altair": ["altair"],
    "Tableau": ["tableau"],
    "Qlik": ["qlik", "qlikview", "qliksense"],
    "Looker": ["looker", "looker studio", "google data studio"],
    "Metabase": ["metabase"],
    "Apache Superset": ["superset", "apache superset"],

    "Jupyter": ["jupyter", "jupyter notebook", "ipynb"],
    "Google Colab": ["colab", "google colab"],

    "pip": ["pip"],
    "Poetry": ["poetry"],
    "Pipenv": ["pipenv"],
    "Conda": ["conda", "anaconda", "miniconda"],
    "virtualenv": ["virtualenv", "venv"],
    "npm": ["npm"],
    "Yarn": ["yarn"],
    "pnpm": ["pnpm"],

    "Jira": ["jira"],
    "Confluence": ["confluence"],
    "Notion": ["notion"],
    "Markdown": ["markdown", "md"],

    "pytest": ["pytest", "py.test"],
    "unittest": ["unittest"],
    "JUnit": ["junit"],
    "TestNG": ["testng"],
    "Gatling": ["gatling"],
    "JMeter": ["jmeter", "apache jmeter"],
    "Locust": ["locust"],
    "k6": ["k6"],

    "PostGIS": ["postgis"],
    "GeoPandas": ["geopandas"],

    "React Native": ["react native"],
    "Expo": ["expo", "@expo"],
    "Flutter": ["flutter"],
    "Android SDK": ["android", "android sdk"],
    "Swift": ["swift"],
    "Objective-C": ["objective-c", "objc"],
    "Electron": ["electron"],
    "Tauri": ["tauri"],

    "Meilisearch": ["meilisearch"],
    "Typesense": ["typesense"],

    "OpenCV": ["opencv", "cv2"],
    "Pillow": ["pillow", "pil"],
    "FFmpeg": ["ffmpeg"],
    "OpenMP": ["openmp"],
    "CUDA": ["cuda", "nvidia cuda"],
    "cuDNN": ["cudnn"],
    "OpenCL": ["opencl"],

    "Great Expectations": ["great expectations", "gx"],
    "Amundsen": ["amundsen"],
    "Apache Atlas": ["atlas", "apache atlas"],
    "Feast": ["feast"],

    "cron": ["cron", "crontab"],
    "Serverless Framework": ["serverless", "serverless framework", "sls"],
    "curl": ["curl"],

    "GitHub": ["github"],
    "GitLab": ["gitlab"],
    "Bitbucket": ["bitbucket"],
    "SVN": ["svn", "subversion"],

    "MinIO": ["minio"],
    "Ceph": ["ceph", "cephfs", "rados"],

    "SMTP": ["smtp"],

    "etcd": ["etcd"],

    "Gunicorn": ["gunicorn"],
    "uWSGI": ["uwsgi", "u wsgi"],
    "ASGI": ["asgi"],
    "WSGI": ["wsgi"],
    "Starlette": ["starlette"],
    "Tornado": ["tornado"],
    "Aiohttp": ["aiohttp"],

    "VS Code": ["vscode", "visual studio code"],
    "PyCharm": ["pycharm"],
    "IntelliJ IDEA": ["intellij", "idea", "intellij idea"],
    "DataGrip": ["datagrip"],

    "New Relic": ["new relic"],
    "Datadog": ["datadog"],
    "SonarQube": ["sonarqube", "sonar"],
    "Snyk": ["snyk"],
    "Trivy": ["trivy"],
    "OWASP": ["owasp", "owasp zap", "zap"],

    "Nexus": ["nexus", "sonatype nexus"],
    "Artifactory": ["artifactory", "jfrog artifactory"],
    "Cloudflare": ["cloudflare"],
    "Harbor": ["harbor"],
    
    "Networking Fundamentals": ["networking", "computer networks", "сетевые основы", "компьютерные сети"],
    "OSI Model": ["osi", "osi model", "модель osi"],
    "TCP/IP": ["tcp ip", "tcpip", "tcp/ip", "стек tcp/ip"],
    "HTTP/HTTPS": ["http", "https", "http 1.1", "http2", "http/2", "http3", "http/3"],
    "DNS": ["dns", "bind", "powerdns", "зона dns", "днс"],
    "DHCP": ["dhcp", "dynamic host configuration"],
    "NAT": ["nat", "pat", "masquerade", "snat", "dnat"],
    "VPN": ["vpn", "site-to-site vpn", "remote access vpn", "виртуальная частная сеть"],
    "IPsec": ["ipsec", "ikev2", "ikev1"],
    "L2TP": ["l2tp"],
    "OpenVPN": ["openvpn"],
    "WireGuard": ["wireguard", "wg"],
    "TLS/SSL": ["tls", "ssl", "x509", "pkix", "pki", "сертификаты ssl", "letsencrypt"],
    "SSH": ["ssh", "openssh"],
    "Telnet": ["telnet"],
    "SNMP": ["snmp", "snmpv2", "snmpv3"],
    "NetFlow/sFlow": ["netflow", "sflow"],
    "Syslog": ["syslog", "rsyslog", "syslog-ng"],
    "Wireshark": ["wireshark", "packet capture", "pcap", "tcpdump"],
    "nmap": ["nmap", "port scanner"],
    "Traceroute/MTR": ["traceroute", "mtr", "tracert"],
    "QoS": ["qos", "quality of service", "traffic shaping"],
    "Proxy": ["proxy", "forward proxy", "reverse proxy", "прокси"],
    "CDN": ["cdn", "content delivery network"],
    "Akamai": ["akamai"],
    "Fastly": ["fastly"],
    "F5 BIG-IP": ["f5", "big-ip", "ltm", "gtm"],
    "Cisco Networking": ["cisco", "ios", "nx-os", "catalyst", "asa"],
    "Juniper": ["juniper", "junos"],
    "MikroTik": ["mikrotik", "routeros"],
    "Ubiquiti": ["ubiquiti", "unifi", "edgerouter"],
    "Routing": ["routing", "маршрутизация", "static routes", "policy based routing"],
    "OSPF": ["ospf", "open shortest path first"],
    "BGP": ["bgp", "border gateway protocol"],
    "EIGRP": ["eigrp"],
    "Switching": ["switching", "коммутация", "layer2"],
    "STP": ["stp", "spanning tree", "rstp", "mstp"],
    "VLAN": ["vlan", "802.1q", "trunk"],
    "802.1X": ["802.1x", "dot1x"],
    "RADIUS": ["radius"],
    "TACACS+": ["tacacs", "tacacs+"],
    "LAN": ["lan", "local area network"],
    "WAN": ["wan", "wide area network"],
    "WLAN/Wi-Fi": ["wifi", "wi-fi", "802.11", "802.11ac", "802.11ax", "wpa2", "wpa3"],
    "Ethernet": ["ethernet", "802.3", "poe", "power over ethernet"],
    "MPLS": ["mpls"],
    "SDN": ["sdn", "software defined networking", "openflow"],
    "Cisco ACI": ["cisco aci", "application centric infrastructure"],
    "Firewall": ["firewall", "iptables", "nftables", "pf", "cisco asa", "palo alto", "fortigate"],
    "IDS/IPS": ["ids", "ips", "snort", "suricata"],
    "LDAP": ["ldap"],
    "Active Directory": ["active directory", "ad", "windows domain"],
    "SAML": ["saml", "saml2"],
    "SSO": ["sso", "single sign-on"],
    "RDP/VNC": ["rdp", "vnc"],
    "FTP/SFTP": ["ftp", "ftps", "sftp"],
    "SCP": ["scp"],
    "TFTP": ["tftp"],
    "NFS": ["nfs"],
    "SMB/CIFS": ["smb", "cifs", "samba"],

    "SAN": ["san", "storage area network"],
    "NAS": ["nas", "network attached storage"],
    "Fibre Channel": ["fibre channel", "fc", "fc san"],
    "iSCSI": ["iscsi"],
    "RAID": ["raid", "raid0", "raid1", "raid5", "raid6", "raid10"],
    "ZFS": ["zfs"],
    "XFS": ["xfs"],
    "ext4": ["ext4"],

    "VMware vSphere/ESXi": ["vmware", "vsphere", "esxi"],
    "Hyper-V": ["hyper-v"],
    "KVM/Libvirt": ["kvm", "libvirt", "qemu-kvm"],
    "Proxmox": ["proxmox"],
    "VirtualBox": ["virtualbox"],

    "Jenkins": ["jenkins"],
    "GitHub Actions": ["github actions", "gha"],
    "GitLab CI/CD": ["gitlab ci", "gitlab cicd"],
    "TeamCity": ["teamcity"],
    "CircleCI": ["circleci"],
    "Travis CI": ["travis ci"],
    "Chef": ["chef"],
    "Puppet": ["puppet"],
    "SaltStack": ["salt", "saltstack"],

    "Veeam": ["veeam"],
    "rsync": ["rsync"],
    "BorgBackup": ["borg", "borgbackup"],
    "Restic": ["restic"],

    "Microsoft Office": ["ms office", "microsoft 365", "office 365", "офисный пакет"],
    "Microsoft Excel": ["excel", "ms excel", "xlookup", "vlookup", "pivot table", "сводные таблицы", "power query", "power pivot", "excel vba", "макросы"],
    "Microsoft Word": ["word", "ms word"],
    "Microsoft PowerPoint": ["powerpoint", "ppt", "ms powerpoint"],
    "Microsoft Outlook": ["outlook", "ms outlook"],
    "Microsoft OneNote": ["onenote"],
    "Microsoft Access": ["access", "ms access"],
    "Microsoft Visio": ["visio"],
    "Microsoft Project": ["ms project", "project"],
    "Google Workspace": ["g suite", "google workspace"],
    "Google Sheets": ["google sheets", "sheets", "гугл таблицы"],
    "Google Docs": ["google docs", "docs", "гугл документы"],
    "Google Slides": ["google slides", "slides", "гугл презентации"],
    "Miro": ["miro"],
    "Figma": ["figma"],
    "Trello": ["trello"],
    "Asana": ["asana"],
    "Monday.com": ["monday", "monday.com"],
    "Slack": ["slack"],
    "Microsoft Teams": ["teams", "ms teams"],
    "Zoom": ["zoom"],
    "Webex": ["webex"],

    "Salesforce": ["salesforce", "sfdc"],
    "HubSpot CRM": ["hubspot", "hubspot crm"],
    "Bitrix24": ["bitrix24", "битрикс24"],
    "amoCRM": ["amocrm", "amo crm"],
    "Zoho CRM": ["zoho crm", "zoхо crm"],
    "Pipedrive": ["pipedrive"],
    "Microsoft Dynamics 365": ["dynamics 365", "ms dynamics"],
    "SAP CRM": ["sap crm"],
    "1C:Enterprise": ["1c", "1с", "1c предприятие", "1с предприятие"],
    "Odoo": ["odoo", "odoo erp"],
    "ServiceNow": ["servicenow", "snow"],
    "Jira Service Management": ["jsm", "jira service desk", "jira service management"],

    "Google Analytics": ["ga", "google analytics", "ga4"],
    "Google Tag Manager": ["gtm", "google tag manager"],
    "Yandex Metrica": ["yandex metrika", "яндекс метрика", "метрика"],
    "Mixpanel": ["mixpanel"],
    "Amplitude": ["amplitude"],
    "Redash": ["redash"],
    "KNIME": ["knime"],
    "Alteryx": ["alteryx"],
    "A/B Testing": ["ab testing", "a/b testing", "split testing", "aa testing", "эксперименты"],
    "Hypothesis Testing": ["hypothesis testing", "statistical testing", "t-test", "chi-square", "х-проверки гипотез"],
    "Cohort Analysis": ["cohort analysis", "когортный анализ"],
    "RFM Analysis": ["rfm", "rfm analysis"],
    "Regex": ["regex", "regular expressions", "регулярные выражения"],

    "VPC": ["vpc", "virtual private cloud"],
    "Security Groups": ["security group", "aws sg", "sg"],
    "NACL": ["nacl", "network acl"],
    "VNet": ["vnet", "azure vnet"],
    "CloudFront": ["cloudfront", "aws cloudfront"],
    "Azure CDN": ["azure cdn"],
    "Cloud DNS": ["cloud dns", "gcp cloud dns", "aws route 53", "route53"],

    "SLI/SLO/SLA": ["sli", "slo", "sla"],
    "PagerDuty": ["pagerduty"],
    "Opsgenie": ["opsgenie"],
}

CANONICAL = tuple(SKILL_LEXICON.keys())

_variants: list[str] = []
for canon, syns in SKILL_LEXICON.items():
    _variants.append(canon)
    _variants.extend(syns)

VARIANTS = tuple(dict.fromkeys(_variants))