services:
  postgres:
    image: postgres:17.0
    env_file: .env
    environment:
      POSTGRES_USER: ${APP_PG__USER}
      POSTGRES_PASSWORD: ${APP_PG__PASSWORD}
      POSTGRES_DB: ${APP_PG__DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - devnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_PG__USER} -d ${APP_PG__DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 20  # Увеличьте количество попыток

  backend:
    env_file: .env
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy  # Ждем пока БД станет здоровой
    networks:
      - devnet

networks:
  devnet:
    name: devnet
    driver: bridge